on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-tk
        pip install -r requirements.txt
    
    - name: Install ROOT Framework
      run: |
        sudo snap install root-framework
  
    - name: Run ROOT Framework
      run: |
        snap run root-framework -b -q -l <<EOF
        .x your_root_script.C
        EOF

    - name: Build executable
      run: pyinstaller --onefile scripts/create_executable.py
    
    - name: List files in dist
      run: ls -la /home/runner/work/visualspectra/visualspectra/dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Create VisualSpectra Executable
        path: /home/runner/work/visualspectra/visualspectra/dist/create_executable