on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install ROOT Framework
      run: |
        git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src
        mkdir root_build
        mkdir root_install
        cd root_build
        cmake -G"Visual Studio 16 2019" -A Win32 -Thost=x64 -DCMAKE_VERBOSE_MAKEFILE=_PREFIX=../root_install ../root_src
        cmake --build . --config Release --target install
        $rootInstallPath = (Resolve-Path ../root_install/bin/thisroot.bat).Path
        & $rootInstallPath

    - name: Build executable
      run: pyinstaller --onefile scripts/create_executable.py
    
    - name: List files in dist
      run: ls -la /home/runner/work/visualspectra/visualspectra/dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Create VisualSpectra Executable
        path: /home/runner/work/visualspectra/visualspectra/dist/create_executable